### ISSUE TITLE
Do you intend to use Pelican at some point?

### ISSUE THREAD

**Issue by naturallymitchell** [sukiletxe/sukiletxe.github.io#2]
(out of curiosity)

**Comment by sukiletxe** [comment]
Not for this repository. I think that the Authomatic Page Generator suffices for a one-page repository anyway. However, I still have to find a theme which I like.
If I finally create a blog, I will use a static website generator, possibly Pelican or Nikola. Let's see if we can fix the issue on the themes of Pelican and, ideally, this gets upstream.
